apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: comic-website
type: Opaque
stringData:
  JWT_SECRET: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_BUCKET_NAME: ""