apiVersion: v1
kind: Secret
metadata:
  name: community-secret
  namespace: comic-website
  labels:
    app: community-service
    environment: production
    component: database
type: Opaque
data:
  # 数据库连接配置
  database-url: ${DATABASE_URL_B64}
  database-host: ${DATABASE_HOST_B64}
  database-port: ${DATABASE_PORT_B64}
  database-name: ${COMMUNITY_DB_NAME_B64}
  database-username: ${COMMUNITY_DB_USERNAME_B64}
  database-password: ${COMMUNITY_DB_PASSWORD_B64}
  
  # JWT 配置
  jwt-secret: ${COMMUNITY_JWT_SECRET_B64}
  jwt-expires-in: Nzg2NDAwMA==  # 7 days in base64 (7864000)
  
  # Redis 配置
  redis-host: ${REDIS_HOST_B64}
  redis-port: ${REDIS_PORT_B64}
  redis-password: ${REDIS_PASSWORD_B64}
  
  # 应用配置
  node-env: cHJvZHVjdGlvbg==  # production in base64
  server-port: MzAwMQ==       # 3001 in base64
  
  # CORS 配置
  cors-origin: aHR0cHM6Ly9jb21pYy13ZWJzaXRlLmV4YW1wbGUuY29t  # https://comic-website.example.com in base64
  
  # 缓存配置
  cache-ttl: MzYwMA==         # 3600 in base64
  cache-enabled: dHJ1ZQ==     # true in base64
  
  # 通知配置
  notification-enabled: dHJ1ZQ==  # true in base64
  email-service-key: ${EMAIL_SERVICE_KEY_B64}
  
  # 实时服务配置
  websocket-enabled: dHJ1ZQ==  # true in base64
  realtime-service-url: aHR0cDovL2NvbW11bml0eS1zZXJ2aWNlOjMwMDE=  # http://community-service:3001 in base64