apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: comic-website
type: Opaque
stringData:
  host: "${RDS_HOST}"
  port: "${RDS_PORT}"
  database: "${RDS_DATABASE}"
  username: "${RDS_USERNAME}"
  password: "${RDS_PASSWORD}"