apiVersion: v1
kind: ServiceAccount
metadata:
  name: community-service-account
  namespace: comic-website
  labels:
    app: community-service
    component: backend
    environment: production
  annotations:
    eks.amazonaws.com/role-arn: COMMUNITY_ROLE_ARN_PLACEHOLDER
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: community-service-role
  labels:
    app: community-service
    component: backend
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: community-service-rolebinding
  labels:
    app: community-service
    component: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: community-service-role
subjects:
- kind: ServiceAccount
  name: community-service-account
  namespace: comic-website
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: community-service-namespaced-role
  namespace: comic-website
  labels:
    app: community-service
    component: backend
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: community-service-namespaced-rolebinding
  namespace: comic-website
  labels:
    app: community-service
    component: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: community-service-namespaced-role
subjects:
- kind: ServiceAccount
  name: community-service-account
  namespace: comic-website