apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comic-website

resources:
  # 命名空间
  - namespaces/comic-website.yaml

  # Service Accounts
  - service-accounts/alb-service-account.yaml
  - service-accounts/backend-service-account.yaml
  - service-accounts/community-service-account.yaml
  - service-accounts/frontend-service-account.yaml

  # Configs & Secrets
  - configs/backend-config.yaml
  - configs/community-configmap.yaml
  - configs/community-db-secret.yaml      # 新增 - 使用占位符
  - configs/auth-secret.yaml              # 新增 - 使用占位符
  - configs/community-secret.yaml         # 新增 - 使用占位符
  - configs/frontend-config.yaml
  - configs/rds-secret.yaml
  - configs/backend-secret.yaml
  - configs/s3-secret.yaml

  # Deployments
  - deployments/backend-deployment.yaml
  - deployments/community-deployment.yaml
  - deployments/frontend-deployment.yaml

  # Services
  - service/backend-service.yaml
  - service/community-service.yaml
  - service/frontend-service.yaml

  # Networking (ALB)
  - networking/alb-ingress-class.yaml
  - networking/alb-ingress.yaml

# 使用 labels 替代 commonLabels
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize