apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comic-website

resources:
  # 命名空间
  - namespaces/comic-website.yaml

  # Service Accounts
  - service-accounts/alb-service-account.yaml
  - service-accounts/backend-service-account.yaml
  - service-accounts/frontend-service-account.yaml

  # Configs & Secrets
  - configs/backend-config.yaml
  - configs/frontend-config.yaml
  - configs/rds-secret.yaml
  - storage/s3-secret.yaml

  # Deployments
  - deployments/backend-deployment.yaml
  - deployments/frontend-deployment.yaml

  # Services
  - service/backend-service.yaml
  - service/frontend-service.yaml

  # Networking (ALB)
  - networking/alb-ingress-class.yaml
  - networking/alb-ingress.yaml

  # Jobs
  - jobs/database-migration.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
