apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-deployment
  namespace: comic-website
  labels:
    app: community-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: community-service
      version: v1
  template:
    metadata:
      labels:
        app: community-service
        version: v1
    spec:
      serviceAccountName: community-service-account
      containers:
      - name: community-service
        image: PLACEHOLDER_COMMUNITY_IMAGE
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: community-db-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt-secret
              name: auth-secret
        - name: AWS_REGION
          value: "us-east-1"
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: bucket-name
              name: s3-secret
        - name: API_BASE_URL
          value: "/api/community"
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: "regional"
        - name: AWS_ROLE_ARN
          valueFrom:
            secretKeyRef:
              key: role-arn
              name: community-secret
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: aws-iam-token
          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          readOnly: true
      volumes:
      - name: aws-iam-token
        projected:
          sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token