apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service
  namespace: comic-app
  labels:
    app: community-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: community-service
  template:
    metadata:
      labels:
        app: community-service
        version: v1
    spec:
      containers:
      - name: community-service
        image: YOUR_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/comic-website-prod-community:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: community-db-secret
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: jwt-secret
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: FRONTEND_URL
          value: "https://your-frontend-domain.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: comic-app
spec:
  selector:
    app: community-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  type: ClusterIP