apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: comic-website
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      serviceAccountName: comic-frontend-sa
      containers:
      - name: frontend
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/comic-website-prod-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_API_URL
        - name: REACT_APP_S3_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_S3_BASE_URL
        - name: REACT_APP_UPLOAD_MAX_SIZE
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_UPLOAD_MAX_SIZE
        - name: REACT_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_VERSION
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3