apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: comic-website
  labels:
    app: backend
    service: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP