apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: comic-website
  labels:
    app: community-service
    version: v1
spec:
  selector:
    app: community-service
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: 3002
    protocol: TCP
  type: ClusterIP